### ISSUE TITLE
애니시아 API 도메인 변경.

### ISSUE THREAD

**Issue by marker-seoul** [qkdxorjs1002/AniSched-Android#6]
https://github.com/anissia-net/document/blob/main/api_anime_schdule.md

애니시아의 프론트와 백엔드 서버 분리에 따라 API 도메인이 변경되었습니다.

기존 : https://anissia.net/api/*
변경 : https://api.anissia.net/*

준비가 완료되어 바로 적용하시면 됩니다.

기존 API는 곧 종료할 예정입니다.

**Comment by marker-seoul** [comment]
@qkdxorjs1002 이제 기존 API 경고 페이지로 바꿔도 될까요?

**Comment by ac-saro** [comment]
@qkdxorjs1002 2월 28일부터는 기존 API 호출 시 이전 되었다는 메시지가 대신 출력 될 예정입니다.

**Comment by marker-seoul** [comment]
@qkdxorjs1002 
3/1 : 기존 API 호출 시 이전 되었다는 메시지가 대신 출력 될 예정입니다.
4/1 : 클라우드 플레어 페이지가 대신 뜰 예정입니다.
(클라우드 플레어 pages에 기존 주소 연계 기능이 없어 API 표시 자체가 불가합니다...)

**Comment by qkdxorjs1002** [comment]
일이 바빠서 신경을 쓰다 못 썼네요 ㅎㅎ
데스크톱 버전 포함해서 알려주신 날짜(3/1) 이전에 배포해서 이용에 문제 없도록 해두겠습니다!
노티 감사드립니다.

**Comment by marker-seoul** [comment]
@qkdxorjs1002 바쁘신 와중에 감사합니다.
혹시 그전에도 완료되면 알려주세요.

**Comment by marker-seoul** [comment]
안녕하세요.

아무래도 작동 안된지 오래되다보니.
https://anissia.net/schedule 에서 제외하겠습니다.

혹시 패치하고 나시면 알려주세요.

**Comment by qkdxorjs1002** [comment]
24~25일 스토어 배포 예정입니다.

**Comment by qkdxorjs1002** [comment]
d5993b3

**Comment by marker-seoul** [comment]
예, 확인되면 링크 다시 열도록하겠습니다.

**Comment by qkdxorjs1002** [comment]
올라갔네요~

**Comment by marker-seoul** [comment]
예, 링크 열었어요.

**Comment by qkdxorjs1002** [comment]
네 고생하십니다!
