### ISSUE TITLE
[긴급] 구글 개발자 계정 정지

### ISSUE THREAD

**Issue by marker-seoul** [qkdxorjs1002/AniSched-Android#7]
최근 구글이 신원인증을 강화하면서
법인이나 개인이 인증되지 않은 계정에 대해
모든 앱을 스토어에서 내렸습니다.

https://developer.android.com/distribute/console 

위 주소로 가셔서 개인 인증을 하시기 바랍니다.
(저 같은 경우는 주민번호 뒷자리가 없는 등본으로 인증이 되었습니다.)

완료되면 연락주시기 바랍니다.

**Comment by qkdxorjs1002** [comment]
@ac-saro 정책이 점점 까다로워지는군요... 해결했습니다, 감사드립니다~
